name: permission_handler
description: Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions.
repository: https://github.com/baseflow/flutter-permission-handler
issue_tracker: https://github.com/Baseflow/flutter-permission-handler/issues
version: 11.2.0

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=2.5.3"

flutter:
  plugin:
    platforms:
      android:
        default_package: permission_handler_android
      ios:
        default_package: permission_handler_apple
      web:
        default_package: permission_handler_html
      windows:
        default_package: permission_handler_windows

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  permission_handler_android:
#     path: "G:/Source/Flutter/MyProject/APA/permission/flutter_permission_handler/permission_handler_android"
      git:
        url: https://github.com/mirshahbazi/permission_handler_android.git
  permission_handler_apple: 
#    path: "G:/Source/Flutter/MyProject/APA/permission/flutter_permission_handler/permission_handler_apple"
      git:
        url: https://github.com/mirshahbazi/permission_handler_apple.git
  permission_handler_windows: ^0.2.1
  permission_handler_platform_interface: ^4.1.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.1
  plugin_platform_interface: ^2.0.0
